apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ts-operator
commonLabels:
  app: ts-operator
resources:
  - ts-operator-namespace.yaml
  - ts-operator-sa.yaml
  - memcached-crd.yaml
  - memcached-editor-role.yaml
  - ts-operator-clusterrolebinding.yaml
  - ts-operator-deployment.yaml
