apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ts-operator
    app.kubernetes.io/component: ts-operator
    app.kubernetes.io/instance: ts-operator
  name: ts-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: ts-operator
  template:
    metadata:
      labels:
        deployment: ts-operator
    spec:
      containers:
        - env:
            - name: DEV_MODE
              value: 'false'
          image: ghcr.io/nielspeter/operator-in-javascript:main
          imagePullPolicy: Always
          name: ts-operator
      serviceAccount: ts-operator
